from .base import Module
from .countdown import Countdown
from .zalgo import Zalgo
from .flip import Flip
from .verify import Verify, McCarthy
from .about import About
from .xkcd import XKCD
from .wideletters import WideLetters
from .jake import Jake
from .carlos import Carlos
from .spaces import Spaces
from .claps import Claps
from .chat import Chat
from .weather import Weather
from .shakespeare import Shakespeare
from .love import Love
from .chose import Chose
from .sad import Sad
from .eightball import EightBall
from .analytics import Analytics
from .pick import Pick
from .meme import Meme
from .system import Welcome, Mourn, Introduce
from .youtube import YouTube
from .price import Price
from .minion import Minion
from .house import House
from .location import Location
from .lyrics import Lyrics
from .nasa import NASA
from .capitalize import Capitalize
from .twitter import Twitter
from .tea import Tea
from .uwu import UWU
from .conversationstarter import ConversationStarter
from .quote import Quote
from .dog import Dog
from .funfact import FunFact
from .funny import Funny
from .kelbo import Kelbo
from .boink import Boink
from .ship import Ship
from .wholesome import Wholesome
from .battery import Battery
from .nato import NATO
from .heaven import Heaven
from .power import Power
from .record import Record
from .colleges import Colleges
from .yalenews import YaleNews
from .circle import Circle
from .jpeg import JPEG
from .deepfry import DeepFry
from .anna import Anna
from .damn import Damn
from .handshake import Handshake
from .dining import Dining
from .building import Building
from .course import Course
from .iam import IAm
from .people import People
from .compliment import Compliment
from .poem import Poem
from .lmgtfy import LMGTFY
from .randomcollege import RandomCollege
from .morse import Morse
from .shield import Shield
from .organizations import Organizations
from .roomnumber import RoomNumber
from .smol import Smol
from .admit import Admit
from .anagram import Anagram
from .isitchickentendersday import IsItChickenTendersDay
from .pdl import PDL
from .doge import Doge
from .cry import Cry
from .coursename import CourseName
from .pickupline import PickUpLine
