"""init

Revision ID: d8376c2d8736
Revises: 
Create Date: 2021-03-10 10:16:22.921418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8376c2d8736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    # ### end Alembic commands ###
